#! /bin/bash

unset LANG

branch=master

if [ "$1" = "--dist" -o "$1" = "--target" ] ; then
  dist="--target $2"
  shift
  shift
fi

if [ "$1" = "--branch" ] ; then
  branch=$2
  shift
  shift
fi

if [ -n "$1" ] ; then
  branch=$1
fi

clean_target=clean
grep -q -s distclean: Makefile* && clean_target=distclean

git status
git checkout $branch
git pull

make $clean_target

if [ -d package ] ; then
  echo 'old archive files found!'
  exit 1
fi

make archive

tobs $dist

make $clean_target
