#! /bin/bash

unset LANG

export USER_NAME=snwint_jenkins

branch=master
[ -n "$1" ] && branch=$1

clean_target=clean
grep -q -s distclean: Makefile* && clean_target=distclean

git status
git checkout $branch
git pull

make $clean_target

if [ -d package ] ; then
  echo 'old archive files found!'
  exit 1
fi

make archive

tobs

make $clean_target
